apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld 
spec:
  template:
    metadata:
      name: helloworld-pod
    spec:
      containers:
      - name: helloworld-container
        image: joyrahman/helloworld_kubernetes:v1
        command: ["python"]
        args: ["/var/app/helloworld.py", "204800","5000"]
      restartPolicy: Never
